@Library('pipelinelib') import org.wikimedia.integration.*

def triggerJobs = ['totally-triggered']

def builder = new PipelineBuilder([allowedTriggerJobs: triggerJobs], ".pipeline/config.yaml")
builder.build(this, params.PLIB_PIPELINE)
