pipelines:
  service1:
    directory: src/service1
    stages:
      - name: unit
        build: test
        run: true
      - name: lint
      - name: candidate
        build: production
        run: false
        publish:
          image: true
    execution:
      - [unit, candidate]
      - [lint, candidate]
  service2:
    directory: src/service2
    stages:
      - name: test
        exports:
          foo: '${setup.timestamp}-${.stage}'
  test-build-options:
    blubberfile: blubber.yaml
    stages:
      - name: test-context-and-excludes
        build:
          variant: service1-checkexcludes
          context: src/service1
          excludes: [Makefile]
  test-checkout-binding:
    stages:
      - name: test
        exports:
          commit: '${setup.commit}'
          branch: '${setup.branch}'
          remote: '${setup.remote}'
  test-command-output:
    blubberfile: blubber.yaml
    stages:
      - name: cat
        build: bash
        run:
          arguments:
            - |-
              cat <<-end
              hey
              you
              end
          tail: 1
      - name: test-it
        build: bash
        run:
          arguments:
            - '[[ "$1" == you* ]]'
            - --
            - '${cat.output}'
